#ifndef PBRSHADER_H
#define PBRSHADER_H

#include <string.h>

using namespace std;

typedef enum {
    SHADER_TYPE_PHONG = 0,
    SHADER_TYPE_BLINN_PHONG,
    SHADER_TYPE_COOK_TORRNACE,
    NUM_SHADER_TYPE
} SHADER_TYPE;


typedef enum {
    PHONG_SHADER_ATTR_VERTEX = 0,
    PHONG_SHADER_ATTR_NORMAL,
    PHONG_SHADER_ATTR_TANGENT,
    PHONG_SHADER_ATTR_BITANGENT,
    PHONG_SHADER_ATTR_TEXCOORD,
    NUM_PHONG_SHADER_ATTR
} PHONG_SHADER_ATTR;

typedef enum {
    PHONG_SHADER_UNIFORM_MVP = 0,
    PHONG_SHADER_UNIFORM_MV,
    PHONG_SHADER_UNIFORM_LIGHT_POS,
    PHONG_SHADER_UNIFORM_VIEW_POS,
    PHONG_SHADER_UNIFORM_AMBIENT,
    PHONG_SHADER_UNIFORM_DIFFUSE,
    PHONG_SHADER_UNIFORM_SPECULAR,
    PHONG_SHADER_UNIFORM_SHINESS,
    PHONG_SHADER_UNIFORM_DEFAULT_COLOR,
    PHONG_SHADER_UNIFORM_TEXTURE_ALBEDO,
    PHONG_SHADER_UNIFORM_TEXTURE_NORMAL_MAP,
    NUM_PHONG_SHADER_UNIFORM
} PHONG_SHADER_UNIFORM;

typedef enum {
  PHONG_PARAMETER_TYPE_SHINESS = 0,
  NUM_PHONG_PARAMETER_TYPE
} PHONG_PARAMETER_TYPE;

const string PBR_SHADER_PATH_PHONG ("../pbr_test/shader/phong");
const string PBR_SHADER_PATH_BLINN_PHONG ("../pbr_test/shader/blinn_phong");

#endif // PBRSHADER_H
